Add shellcheck ci and fix flattool script according to shellcheck

diff --git a/flattool b/flattool
--- a/flattool
+++ b/flattool
@@ -9,22 +9,22 @@ appID=''
 # ====================================================================================
 # Making a println function because I cannot be asked to remember to add \n every time
 println() {
-    printf -- "$*\n"
+    printf -- "%s\n" "$*"
 }
 
 # Function to make printing error message easier
 printerr() {
-    printf "\033[1;31merror:\033[0m $1\n\n"
+    printf "\033[1;31merror:\033[0m %s\n\n" "$1"
 
     if [ $# -eq 2 ]; then
-        printf "${2}\n"
+        printf "%s\n" "$2"
     fi
 }
 
 # Get explicit concent function
 userConcent() {
     prompt=$1
-    printf -- "$prompt [y|N]: "
+    printf -- "%s [y|N]: " "$prompt"
     read -r answer
     case "$answer" in
         [Yy])
@@ -40,27 +40,27 @@ userConcent() {
 
 # Information printing function
 printinfo() {
-    printf -- "  Version\t${versionNumber}\n"
-    printf -- "  Location\t${0}\n\n"
+    printf -- "  Version\t%s\n" "$versionNumber"
+    printf -- "  Location\t%s\n\n" "$0"
 }
 
 # Function to easily check that the command called has the right amount of arguments
 checkArgLength() {
-    minLnegth=$1
+    minLength=$1
     maxLength=$2
-    if [ $minLnegth -lt 0 ] || ( [ $minLnegth -gt $maxLength ] && [ $maxLength -ge 0 ] ); then
+    if [ "$minLength" -lt 0 ] || { [ "$minLength" -gt "$maxLength" ] && [ "$maxLength" -ge 0 ]; }; then
         printerr "Internal program error: checkArgLength called with improper min or max values\n$0"
         exit 1
     fi
     shift
     shift
     shift
-    if [ $# -lt $minLnegth ]; then
-        print_subcommand_help $subcommand
+    if [ $# -lt "$minLength" ]; then
+        print_subcommand_help "$subcommand"
         exit 1
     fi
 
-    if [ $maxLength -ge 0 ] && [ $# -gt $maxLength ]; then
+    if [ "$maxLength" -ge 0 ] && [ $# -gt "$maxLength" ]; then
         print_subcommand_help
         exit 1
     fi
@@ -173,7 +173,7 @@ esac
 # ====================================================================================
 identifyByQuery() {
     app=$(flatpak list | awk -v app="${1,,}" -F '\t' 'tolower($0) ~ app { print $2 }' | head -n 1)
-    if [ -z $app ]; then
+    if [ -z "$app" ]; then
         printerr "No Application ID found from query: '\033[1m${1}\033[0m'"
 
         exit 1
@@ -193,7 +193,7 @@ searchApp() {
 installApp() {
     # Do multiple flatpak installs for multiple apps
     while [ $# -gt 0 ]; do
-        flatpak install $1
+        flatpak install "$1"
         println
         shift
     done
@@ -202,31 +202,30 @@ installApp() {
 removeApp() {
     # Do multiple flatpak removes for multiple apps
     while [ $# -gt 0 ]; do
-        flatpak remove $1
+        flatpak remove "$1"
         println
         shift
     done
 }
 
 purgeApp() {
-    identifyByQuery $1
+    identifyByQuery "$1"
     userConcent "Are you sure you want to uninstall \033[1m${appID}\033[0m and move its user data to the trash?"
-    flatpak uninstall $appID
-    gio trash $HOME/.var/app/$appID
+    flatpak uninstall "$appID"
+    gio trash "${HOME}/.var/app/${appID}"
 }
 
 fixOprphans() {
     println "Checking '~/.var/app' for orphaned folders..."
     orphanedAppsList=''
     while read -r i; do
-        currentApp=$(flatpak list | grep -F "$i")
-        if [ $? -ne 0 ]; then
+        if ! flatpak list | grep -F "$i"; then
             orphanedAppsList="${orphanedAppsList} $i"
         fi
     done < <(ls ~/.var/app)
 
     if [ -n "$orphanedAppsList" ]; then
-        orphanedAppsList=($orphanedAppsList)
+        orphanedAppsList=("$orphanedAppsList")
         println "These user data folders exist with no installed flatpaks:"
         for element in "${orphanedAppsList[@]}"; do
             printf '%s\n' "$element"
@@ -238,16 +237,16 @@ fixOprphans() {
 
         totalOfOrphans=${#orphanedAppsList[@]}
         maxChoices=2
-        if [ $totalOfOrphans -gt 1 ]; then
+        if [ "$totalOfOrphans" -gt 1 ]; then
             println "  3) Decide for each folder individually"
             maxChoices=3
         fi
 
-        printf "\nWhich option do you want to use (0 to abort)? [0-$maxChoices]: "
+        printf "\nWhich option do you want to use (0 to abort)? [0-%s]: " "$maxChoices"
         while true; do
             read -r answer
             if ! [ "$answer" -eq "$answer" ] 2>/dev/null || [ "$answer" -lt 0 ] || [ "$answer" -gt "$maxChoices" ]; then
-                printf "Which option do you want to use (0 to abort)? [0-$maxChoices]: "
+                printf "Which option do you want to use (0 to abort)? [0-%s]: " "$maxChoices"
             else
                 break
             fi
@@ -261,19 +260,19 @@ fixOprphans() {
             2)
                 println "Trashing"
                 for element in "${orphanedAppsList[@]}"; do
-                    gio trash "$HOME/.var/app/$element"
+                    gio trash "${HOME}/.var/app/${element}"
                 done
                 ;;
             3)
                 for element in "${orphanedAppsList[@]}"; do
-                    println "For folder '$element', choose an option"
+                    println "For folder '%s', choose an option" "$element"
                     printf "[T]rash, [I]install, or [S]kip: "
                     while true; do
                         read -r answer
                         case "$answer" in
                             [tT])
                                 println "Trashing"
-                                gio trash "$HOME/.var/app/$element"
+                                gio trash "${HOME}/.var/app/${element}"
                                 break
                                 ;;
                             [iI])
@@ -309,42 +308,42 @@ if [ $# -eq 0 ]; then
 fi
 
 # Calling the correct subcommand help responses
-if [ "$#" -gt 0 ] && [ "${@:$#}" = "-h" -o "${@:$#}" = "--help" ]; then
+if [ "$#" -gt 0 ] && [ "${*:$#}" == "-h" ] || [ "${*:$#}" == "--help" ]; then
     if [ "$#" -eq 1 ]; then
         printMasterHelp
         exit 0
     fi
-    print_subcommand_help $subcommand
+    print_subcommand_help "$subcommand"
     exit 0
 fi
 
 # Switch case to run the proper function per subcommand
 case "$subcommand" in
     id)
-        checkArgLength 1 1 $*
-        identifyByQuery $2
-        println $appID
+        checkArgLength 1 1 "$*"
+        identifyByQuery "$2"
+        println "$appID"
         ;;
     run)
-        checkArgLength 1 1 $*
-        identifyByQuery $2
-        flatpak run $appID
+        checkArgLength 1 1 "$*"
+        identifyByQuery "$2"
+        flatpak run "$appID"
         ;;
     install)
-        checkArgLength 1 -1 $*
+        checkArgLength 1 -1 "$*"
         shift
         installApp "$@"
         ;;
     uninstall)
-        checkArgLength 1 -1 $*
+        checkArgLength 1 -1 "$*"
         shift
         removeApp "$@"
         ;;
     purge)
-        purgeApp $2
+        purgeApp "$2"
         ;;
     search)
-        searchApp $2
+        searchApp "$2"
         ;;
     orphans)
         fixOprphans
